src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Repository\AdRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Une autre annonce possède déjà ce titre, merci de le modifier "
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères !",
     * maxMessage="Le titre ne peut pas faire plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description ne peut pas faire moins de 100 caractères !")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initiliser le slug avant de persist
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug(){
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupéré le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * @return Comment | null
     */
    public function getCommentFromAuthor(User $author){
        foreach ($this->comments as $comments){
            if($comments->getAuthor() === $author) return $comments;
        }
        return null;
    }

    /**
     * Permet d'obtenir la moyenne des notes globales d'une annonce
     *
     * @return float|int
     */
    public function getAvgRatings(){
        // Calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment){
            return $total + $comment->getRating();
        }, 0);

        // Faire la division pour avoir la moyenne
        if(count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas dispo pour cette annonces
     * @return array Un tableau d'objet DateTime représentant les jours d'occupations
     */
    public function getNotAvailableDays(){

        $notAvailableDays = [];

        foreach ($this->bookings as $booking){
            // Calculer les jours qui se trouvent entre la date d'arrivée et de départ
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
                // Calcule tout les Timestamp qui existe pour chaque journée
                // entre la date d'arriver et celle de départ
            );

            // Tableau qui permet de transformer le Timestamp en véritable date
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/Booking.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Votre date doit être au bon format")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être supérieure à la date du jour", groups={"Frontend"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Votre date doit être au bon format")
     * @Assert\GreaterThan(propertyPath="startDate", message="Date de départ choisie inférieure à la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @throws \Exception
     */
    public function prePersist()
    {
        if(empty($this->createdAt)){
            $this->createdAt = new DateTime();
        }
        if(empty($this->amount)){
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration(){
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    /**
     * Check Reservation Possible
     */
    public function isBookableDates(){
        // Recup Tableau des jours occupés + Tableau des jours dans reservation
        $notAvailableDays = $this->ad->getNotAvailableDays();
        $bookingDays = $this->getDays();

        // Formattage Jours
        $formatDay = function($day){
            /** @var DateTime $day */
            return $day->format('Y-m-d');
        };
        $days = array_map($formatDay, $bookingDays);
        $notAvailable = array_map($formatDay, $notAvailableDays);

        // Comparaison jours dans reservation et jours occupés
        foreach($days as $day){
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Jours dans reservation
     * @return array
     */
    public function getDays(){
        $result = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function($dayTimestamp){
            return new DateTime(date('Y-m-d', $dayTimestamp));
        }, $result);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends ApplicationType
{
    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer){
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration("Date d'arrivée", ""))
            ->add('endDate', TextType::class, $this->getConfiguration("Date de départ", ""))
            ->add('comment', TextAreaType::class, $this->getConfiguration(false, "Commentaire facultatif concernant votre réservation", ["required" => false]))
        ;

        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => [
                'Default',
                'Frontend'
            ]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\BookinkType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Internal\CommitOrderCalculator;
use http\Env\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad,Request $request, EntityManagerInterface $manager){

        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking, [
            'validation_groups'=>["Default","Frontend"]
        ]);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $user = $this->getUser();

            $booking->setBooker($user)
                    ->setAd($ad);

            // Si les dates ne sont pas dispo, message d'erreur
            if(!$booking->isBookableDates()){
                $this->addFlash(
                    'warning',
                    "Les dates choisis ne sont plus disponible."
                );
            }else {
                // Sinon enregistrement et redirection
                $manager->persist($booking);
                $manager->flush();

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(),
                    'withAlert' => true]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad'=> $ad,
            'form'=> $form->createView()
        ]);
    }

    /**
     * Permet d'afficher la page de réservation
     *
     * @Route("/booking/{id}", name="booking_show")
     *
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $manage
     * @return Response
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $manager){

        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                "Votre commentaire a bien été "
            );
        }


        return $this->render('booking/show.html.twig', [
            'booking'=> $booking,
            'form'   => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %} Réservation de : {{ ad.title }} {% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
{% endblock %}

{% block body %}

    <div class="container">
        <h1>Effectuer une réservation pour l'annonce : <br> <em>{{ ad.title }}</em></h1>

        <p>Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong></p>

        {{ form_start(form) }}

        <div class="alert alert-light">
            <h4>Choisissez les dates d'arrivée et de départ pour votre réservation</h4>
            <hr>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>
        </div>

        <div class="alert alert-light">
            <h4 class="mt-2">Montant du séjour : <span id="amount">...</span> &euro;</h4>
            <span id="days">0</span> nuit(s) à {{ ad.price | number_format(2, ',', ' ') }} par nuit
            <hr>

            <h4 class="mt-4">Commentaire</h4>
            {{ form_row(form.comment) }}
        </div>

        <p>Pour toutes autres questions, n'hésitez pas à nous contacter</p>
        <button type="submit" class="btn btn-success col-12">Valider votre réservation</button>

        {{ form_end(form) }}
    </div>

{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script>
        $(document).ready(function(){
            const dateSelect = $('#booking_startDate, #booking_endDate');
            dateSelect.datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });
            dateSelect.on('change', calcAmount);
        });
        function calcAmount(){
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            if(startDate && endDate && startDate < endDate){
                const DAY_TIME =  24 * 60 * 60 * 1000;
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ ad.price }};
                $('#days').text(days);
                $('#amount').text(amount.toLocaleString());
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
    {% extends 'base.html.twig' %}

    {% block title %}Réservation n°: {{ booking.id }}{% endblock %}

    {% block body %}

        {% set ad = booking.ad %}
        {% set author = ad.author %}

        <div class="container">
            <h1 class="my-5">Vôtre réservation (n°{{ booking.id }})</h1>

            {% if app.request.query.get('withAlert') %}
                <div class="alert alert-success">
                    <h4 class="alert-heading">Bravo !</h4>
                    <p>
                        Votre réservation auprès de
                        <strong>
                            <a href="{{ path('user_show', {'slug': author.slug}) }}">
                                {{ author.fullName }}
                            </a>
                        </strong>
                        pour l'annonces
                        <strong>
                            <a href="{{ path('ads_show', { 'slug': ad.slug}) }}">{{ ad.title }}</a>
                        </strong>
                        a bien été prise en compte !
                    </p>
                </div>
            {% endif %}

            <div class="row bm-3">
                <div class="col">
                    <div class="alert alert-light">
                        <h2>Détails</h2>
                        <dl class="row">
                            <dt class="col-md-4">Numéro</dt>
                            <dd class="col-md-8">{{ booking.id }}</dd>
                            <dt class="col-md-4">Date d'arrivée</dt>
                            <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                            <dt class="col-md-4">Date de départ</dt>
                            <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                            <dt class="col-md-4">Nombre de nuits</dt>
                            <dd class="col-md-8">{{ booking.duration}}</dd>
                            <dt class="col-md-4">Montant total</dt>
                            <dd class="col-md-8">{{ booking.amount | number_format(2, ',', ' ') }} &euro;</dd>
                            <dt class="col-md-4">Commentaire</dt>
                            <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire')}}</dd>
                        </dl>

                        <hr>

                        <h2 class="alert-heading">Votre hôte</h2>

                        <div class="row mb-3">
                            <div class="col-3">
                                <img src="{{ author.picture }}" class="avatar avatar-medium" alt="Avatar de {{ author.fullName }}">
                            </div>
                            <div class="col-9">
                                <h4>
                                    <a href="{{ path('user_show', {'slug': author.slug }) }}">{{ author.fullName }}</a>
                                </h4>

                                <span class="badge badge-primary">{{ author.ads | length }} annonces</span>
                            </div>
                        </div>
                        {{ author.description | raw }}

                        <a href="{{ path('user_show', {'slug': author.slug}) }}" class="btn btn-primary">
                            Plus d'infos sur {{ author.firstName }}
                        </a>
                    </div>

                    <div class="alert alert-light" id="comment">
                        <h2 class="alert-heading">Votre avis compte !</h2>
                        {% if date() > date(booking.endDate) %}
                            {% set comment = booking.ad.commentFromAuthor(app.user) %}
                            {% if comment is not null %}
                                <blockquote>
                                    {{ comment.content }}K
                                </blockquote>
                                <strong>note :</strong>
                                {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings }%}
                            {% else %}
                                {{ form_start(form) }}
                                {{ form_widget(form) }}
                                <button type="submit" class="btn btn-success">Envoyer votre commentaire</button>
                                {{ form_end(form) }}
                            {% endif %}
                        {% else %}
                        <p>Vous ne pourrez pas noter cette annonce tant que votre voyage n'est pas terminé</p>
                        {% endif %}
                    </div>
                </div>
                <div class="col">
                    <div class="alert alert-light">
                        <h2 class="alert-heading">Votre hébergement</h2>
                        <h4>
                            <a href="{{ path('ads_show', { 'slug': ad.slug}) }}">{{ ad.title }}</a>
                        </h4>

                        <img src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}" class="img-fluid">
                        
                        {{ ad.content | raw }}

                        <a href="{{ path('ads_show', { 'slug': ad.slug}) }}" class="btn btn-primary">Plus d'information</a>
                    </div>
                </div>
            </div>
        </div>

    {% endblock %}